name: Generate SBOM
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: craci
    steps:
      - uses: cracicorp/setup@v1
        with:
          size: "4"
          image: "default"
      - uses: actions/checkout@v4
      - run: make build
